[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
#command = "foot --app-id foot-dropterm"
class = "kitty-dropterm"
margin = 50
size = "70% 60%"
